### PR TITLE
BUILD: Allow disabling individual engines

### PR DESCRIPTION
**Pull request by ccawley2011**
This is currently a work in progress, but I opened this PR anyway in order to get feedback.

What I need to do before this can be merged:
- [x] Allow disabling liblzma and libxml2
- [x] Engines that require libraries that are unavailable should automatically be disabled
- [x] Implement this with CMake

Any thoughts?

### CODE REVIEW

**Comment by DrMcCoy** [comment]
Also keep in mind that the relevant unit tests need to be skipped it libxml2 and liblzma are disabled.

I wish there was a better way than to test ENABLED_* three times, two of those in engines.cpp (and I already wasn't happy that we need both the include and the createEnginesProbe() line), but I don't think there *is* a better way. Just one test, one line and all is said and done for that engine would be great. But this is very nitpicky, yes.

All in all, this looks like what I was imagining for this feature, yes. Maybe a more "beautiful" way to format the summary at the end, but again, just a nitpick.

**Comment by ccawley2011** [comment]
This should hopefully be complete now.

**Comment by clone2727** [comment]
Instead of adding all the checks to the code that uses LZMA, XML, etc., the source files should be excluded in the `rules.mk` file and the header files should have the `#ifdef` checks instead. No need to compile files we're not using and this prevents other (new) code from accidentally using the header files.

**Comment by ccawley2011** [comment]
Done.

**Comment by ccawley2011** [comment]
Any update on this?

**Comment by DrMcCoy** [comment]
Oh, right, completely forgot about this, sorry. I'll see that I'll take another look at this soon

**Comment by DrMcCoy** [comment]
(Either GitHub just ate my comment or I'm getting tired...or both)

I completely forgot about this, sorry. I'll see that I take another look at it soon

**Comment by ccawley2011** [comment]
> Can you instead print both the engine and the feature list with AS_ECHO()? Add a newline in between the normal configure output and the engine list too, and between the engine list and the features list.

Done.

> I've been thinking about the --enable-* options as well. Not for this PR, but for a future one: ideally, they should have three values: on, off, auto.
[...]

Sounds like a good idea. I'll look into it.

**Comment by DrMcCoy** [comment]
Merged as 4db128361...49c9328e5, thanks! :)

**Pull request closed without merging**
