### PR TITLE
NWN2: Add level stat storage to Creature class

### PR DESCRIPTION
**Pull request by rjshae**
This revision will add the level stat data from a creature data file to the Creature class instance, which will allow negative levels to be dynamically applied in game and the creature stats adjusted accordingly. It includes a test in the form of a 4th level Rogue PC built in the game engine.

### CODE REVIEW

**Comment by rjshae** [comment]
Yes, I tried earlier to resolve some of those issues earlier, but it didn't take for some reason. (I did a rebase, edit, re-arrange, squash.) Still haven't mastered git it appears.

**Comment by rjshae** [comment]
A style-checker script would be handy.

**Comment by rjshae** [comment]
Style concerns addressed, I believe.

**Comment by DrMcCoy** [comment]
Yes, looks good now. Merged as 8bda31121...536c65de8, thanks! :)

**Pull request closed without merging**
