### PR TITLE
KOTOR: Add spinning map arrow

### PR DESCRIPTION
**Pull request by Nostritius**
This PR makes the arrow in the minimap spin around on the camera angle.

### CODE REVIEW

**Comment by DrMcCoy** [comment]
You're not resetting the orientation on module change.

That means when you rotate the camera and with it the arrow, and then load another module (for example via loadmodule console command), the arrow starts to point in the wrong direction.

**Comment by Nostritius** [comment]
this problem should now be fixed by setting the current rotation on entering an area.

**Comment by DrMcCoy** [comment]
...It still doesn't work, though. The arrow still moves side-ways and weird upon changing the areas

**Comment by Nostritius** [comment]
The rotation was not applied depending on the north axis. Ichanged this, and now the arrow should rotate different depending on the North Axis.

**Comment by DrMcCoy** [comment]
Nice, this looks good now.

Merged, thanks! :)

**Pull request merged**
