### PR TITLE
COMMON: Use C++11 mutexes and friends

### PR DESCRIPTION
**Pull request by seedhartha**

### CODE REVIEW

**Comment by ccawley2011** [comment]
C++11 threads and mutexes aren't available with MinGW32 (and potentially other platforms as well). As such, I would much prefer it if you still retained the old Common::Mutex classes, so that an alternative replacement could easily be implemented on those platforms.

**Comment by seedhartha** [comment]
That's a valid point. I'd say we need to evaluate those platforms on a case-by-case basis, whether we want to support them or not. IMHO, not using C++11 at its fullest does not make sense to me. I mean, the standard is pretty old and should by now be well supported on all major platforms. Why would you want to use MinGW32 and not MinGW-w64, which does support threads and mutexes?

**Comment by DrMcCoy** [comment]
Huh, last I checked, the original MinGW (aka mingw32) was dead. I couldn't find an up-to-date gcc, and the mess of directories on Sourceforge was confusing. MinGW-w64 was advertised as the better alternative, and I could set up a cross-compiling MinGW-w64 on my Linux box no problem.

Seems like they moved to OSDN now, and there's gcc 8.2 packages?

On the other hand, them not providing full C++11 support is...unfortunate. I was kind of hoping that, by moving to C++11, we could remove some of our dependencies on Boost (Boost.Atomic, for example, was a huge problem for multiple distributions when I was still using the OpenSuSE Build Services) and our custom classes like ScopedPtr (in favour of std::unique_ptr). My thought was, since we depend on C++11 anyway, we can be guaranteed to have these C++11 features everywhere where we can build in the first place.

What other platforms provide C++11 language features like auto, ranged-based for loops and lambdas, which we already use, but don't support std::thread?

**Comment by DrMcCoy** [comment]
Hmm, well, I guess I was too sure of myself here as well :P

I just tried to compile the current xoreos master with my mingw crosscompiler, and it complains about not knowing std::thread. I guess my mingw-w64 is too old? Or I messed up building it?

I really need to fix that and re-build my crosscompiler, with working std::thread. That's even a blocker for the next release we've been thinking about, I'd say.

Feel free to laugh at me now :P

**Comment by DrMcCoy** [comment]
(Okay, I managed to rebuild my cross-compiling MinGW-w64, now a gcc 8.3.0, and std::thread works. Now I just need to rebuild all the library dependencies for xoreos...)

**Comment by seedhartha** [comment]
Just tried cross-compiling a simple program on Ubuntu Bionic (current LTS), and apparently the default mingw-w64 package there does not have C++11 threads either. I guess it would not be a bad idea to revert to SDL and Boost threading after all.

**Comment by seedhartha** [comment]
Or, as a workaround, we could look at [this ](https://github.com/meganz/mingw-std-threads) repository.

**Comment by DrMcCoy** [comment]
Ah: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=757259

> gcc-mingw-w64 now supports both POSIX and Win32-based threading models, with
> the latter by default (to avoid introducing dependencies on the pthreads
> DLL). You can switch the default by running
> 
> 	update-alternatives --config i686-w64-mingw32-gcc
> 
> and/or
> 
> 	update-alternatives --config x86_64-w64-mingw32-gcc
> 
> and the various other compilers as appropriate. You can also explicitly use
> i686-w64-mingw32-gcc-posix (and likewise for the other compilers).
> 
> This is all supposed to be documented in README.Debian but I notice now that
> that file is not installed...

**Comment by seedhartha** [comment]
Yeah, that works for Ubuntu. So, what do we do about it: revert to SDL, use mingw-std-threads or simply deny support for older MinGW platforms?

**Comment by DrMcCoy** [comment]
If we include mingw-std-threads, does std::thread then simply work for all cases without clashing?

I.e. use the existing implementation if it has one, and engage mingw-std-threads if not? Because that looks like a good solution to me.

I'd like to put these checks https://github.com/xoreos/xoreos/pull/496/commits/e4a883a9c66f5fd52f334a5e05d04c3ebc912029#diff-447ea3574f8f6cd5ba143baa884706cbR50 into their own header, though,, so that we don't have to repeat them everywhere. A common/mutex.h with that bit, a common/condition_variable.h for its check, etc. Similar to the old atomic.h to work around the boost issue.

**Comment by DrMcCoy** [comment]
Yeah, looks good to me. Works on all my cross-compilers (including the mingw without native std::threads and the one with). Merged as c378a1adf...0652789d3, thanks! :)

A few things I've changed/added:
- src/common/threads.cpp also needed the check/include
- As a library we include instead of just dynamically link against, it needs its own bigger section in the AUTHORS file
- You typo'd the name of the LICENSE file in the rules.mk, which breaks make dist
- Added the files to the Debian copyright file (2ba78e00c)
- Added linking against libwinpthread (332d203ef) on for MinGW builds with native std::thread
- Removed the now unnecessary SDL_timer include in src/common/thread.cpp (e13054f65)

**Pull request closed without merging**
