### PR TITLE
KOTOR: Shader-based rendering

### PR DESCRIPTION
**Pull request by seedhartha**
This PR enables shader-based skeletal animation in KotOR games.

### CODE REVIEW

**Comment by DrMcCoy** [comment]
Neat :)

There's a few warnings, though, that I'd like you to fix: https://travis-ci.org/xoreos/xoreos/jobs/454244700#L1621 . The "unused parameter" ones, by wrapping them in `UNUSED()`, and the unhandled enum values.

KotOR also crashes for me, within the nvidia drivers:
```
AddressSanitizer:DEADLYSIGNAL
=================================================================
==19966==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x7f0031436ed5 bp 0x00000000000c sp 0x7ffc6f49d690 T0)
==19966==The signal is caused by a READ memory access.
==19966==Hint: address points to the zero page.
    #0 0x7f0031436ed4  (/usr/lib64/libnvidia-glcore.so.410.73+0xf48ed4)
    #1 0x7f0031448fe5  (/usr/lib64/libnvidia-glcore.so.410.73+0xf5afe5)
    #2 0x7f0030fef50a  (/usr/lib64/libnvidia-glcore.so.410.73+0xb0150a)
    #3 0x559ca01594bd in Graphics::Mesh::Mesh::renderImmediate() /home/drmccoy/projects/xoreos/xoreos/src/graphics/mesh/mesh.cpp:173
    #4 0x559ca012bcee in Graphics::Shader::ShaderRenderable::renderImmediate(glm::tmat4x4<float, (glm::precision)0> const&, float) /home/drmccoy/projects/xoreos/xoreos/src/graphics/shader/shaderrenderable.cpp:160
    #5 0x559c9fbf47ad in Graphics::Aurora::BorderQuad::renderImmediate(glm::tmat4x4<float, (glm::precision)0> const&) /home/drmccoy/projects/xoreos/xoreos/src/graphics/aurora/borderquad.cpp:274
    #6 0x559c9faa556e in Graphics::GraphicsManager::renderGUIShader(Graphics::GraphicsManager::ScalingType, Graphics::QueueType, bool) /home/drmccoy/projects/xoreos/xoreos/src/graphics/graphics.cpp:1165
    #7 0x559c9fab9ee5 in Graphics::GraphicsManager::renderScene() /home/drmccoy/projects/xoreos/xoreos/src/graphics/graphics.cpp:1234
    #8 0x559c9f6abf98 in Events::EventsManager::runMainLoop() /home/drmccoy/projects/xoreos/xoreos/src/events/events.cpp:349
    #9 0x559c9e6800af in main /home/drmccoy/projects/xoreos/xoreos/src/xoreos.cpp:184
    #10 0x7f0038698ae6 in __libc_start_main ../csu/libc-start.c:308
    #11 0x559c9e696449 in _start (/mnt/ramdisk/xoreos/src/xoreos+0x4038449)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (/usr/lib64/libnvidia-glcore.so.410.73+0xf48ed4) 
==19966==ABORTING
```

As does Jade Empire when moving around in the area for a bit:
```
==21108==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x62e0000243f8 at pc 0x55a9cfd21fae bp 0x7ffd957c9b30 sp 0x7ffd957c9b20
READ of size 4 at 0x62e0000243f8 thread T0
    #0 0x55a9cfd21fad in Graphics::Render::compareDepth(Graphics::Render::RenderQueue::RenderQueueNode const&, Graphics::Render::RenderQueue::RenderQueueNode const&) /home/drmccoy/projects/xoreos/xoreos/src/graphics/render/renderqueue.cpp:54
    #1 0x55a9cfd43f9c in bool __gnu_cxx::__ops::_Iter_comp_iter<bool (*)(Graphics::Render::RenderQueue::RenderQueueNode const&, Graphics::Render::RenderQueue::RenderQueueNode const&)>::operator()<__gnu_cxx::__normal_iterator<Graphics::Render::RenderQueue::RenderQueueNode*, std::vector<Graphics::Render::RenderQueue::RenderQueueNode, std::allocator<Graphics::Render::RenderQueue::RenderQueueNode> > >, __gnu_cxx::__normal_iterator<Graphics::Render::RenderQueue::RenderQueueNode*, std::vector<Graphics::Render::RenderQueue::RenderQueueNode, std::allocator<Graphics::Render::RenderQueue::RenderQueueNode> > > >(__gnu_cxx::__normal_iterator<Graphics::Render::RenderQueue::RenderQueueNode*, std::vector<Graphics::Render::RenderQueue::RenderQueueNode, std::allocator<Graphics::Render::RenderQueue::RenderQueueNode> > >, __gnu_cxx::__normal_iterator<Graphics::Render::RenderQueue::RenderQueueNode*, std::vector<Graphics::Render::RenderQueue::RenderQueueNode, std::allocator<Graphics::Render::RenderQueue::RenderQueueNode> > >) /usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/include/g++-v8/bits/predefined_ops.h:143
    #2 0x55a9cfd43f9c in __gnu_cxx::__normal_iterator<Graphics::Render::RenderQueue::RenderQueueNode*, std::vector<Graphics::Render::RenderQueue::RenderQueueNode, std::allocator<Graphics::Render::RenderQueue::RenderQueueNode> > > std::__unguarded_partition<__gnu_cxx::__normal_iterator<Graphics::Render::RenderQueue::RenderQueueNode*, std::vector<Graphics::Render::RenderQueue::RenderQueueNode, std::allocator<Graphics::Render::RenderQueue::RenderQueueNode> > >, __gnu_cxx::__ops::_Iter_comp_iter<bool (*)(Graphics::Render::RenderQueue::RenderQueueNode const&, Graphics::Render::RenderQueue::RenderQueueNode const&)> >(__gnu_cxx::__normal_iterator<Graphics::Render::RenderQueue::RenderQueueNode*, std::vector<Graphics::Render::RenderQueue::RenderQueueNode, std::allocator<Graphics::Render::RenderQueue::RenderQueueNode> > >, __gnu_cxx::__normal_iterator<Graphics::Render::RenderQueue::RenderQueueNode*, std::vector<Graphics::Render::RenderQueue::RenderQueueNode, std::allocator<Graphics::Render::RenderQueue::RenderQueueNode> > >, __gnu_cxx::__normal_iterator<Graphics::Render::RenderQueue::RenderQueueNode*, std::vector<Graphics::Render::RenderQueue::RenderQueueNode, std::allocator<Graphics::Render::RenderQueue::RenderQueueNode> > >, __gnu_cxx::__ops::_Iter_comp_iter<bool (*)(Graphics::Render::RenderQueue::RenderQueueNode const&, Graphics::Render::RenderQueue::RenderQueueNode const&)>) /usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/include/g++-v8/bits/stl_algo.h:1905
    #3 0x55a9cfd43f9c in __gnu_cxx::__normal_iterator<Graphics::Render::RenderQueue::RenderQueueNode*, std::vector<Graphics::Render::RenderQueue::RenderQueueNode, std::allocator<Graphics::Render::RenderQueue::RenderQueueNode> > > std::__unguarded_partition_pivot<__gnu_cxx::__normal_iterator<Graphics::Render::RenderQueue::RenderQueueNode*, std::vector<Graphics::Render::RenderQueue::RenderQueueNode, std::allocator<Graphics::Render::RenderQueue::RenderQueueNode> > >, __gnu_cxx::__ops::_Iter_comp_iter<bool (*)(Graphics::Render::RenderQueue::RenderQueueNode const&, Graphics::Render::RenderQueue::RenderQueueNode const&)> >(__gnu_cxx::__normal_iterator<Graphics::Render::RenderQueue::RenderQueueNode*, std::vector<Graphics::Render::RenderQueue::RenderQueueNode, std::allocator<Graphics::Render::RenderQueue::RenderQueueNode> > >, __gnu_cxx::__normal_iterator<Graphics::Render::RenderQueue::RenderQueueNode*, std::vector<Graphics::Render::RenderQueue::RenderQueueNode, std::allocator<Graphics::Render::RenderQueue::RenderQueueNode> > >, __gnu_cxx::__ops::_Iter_comp_iter<bool (*)(Graphics::Render::RenderQueue::RenderQueueNode const&, Graphics::Render::RenderQueue::RenderQueueNode const&)>) /usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/include/g++-v8/bits/stl_algo.h:1923
    #4 0x55a9cfd43f9c in void std::__introsort_loop<__gnu_cxx::__normal_iterator<Graphics::Render::RenderQueue::RenderQueueNode*, std::vector<Graphics::Render::RenderQueue::RenderQueueNode, std::allocator<Graphics::Render::RenderQueue::RenderQueueNode> > >, long, __gnu_cxx::__ops::_Iter_comp_iter<bool (*)(Graphics::Render::RenderQueue::RenderQueueNode const&, Graphics::Render::RenderQueue::RenderQueueNode const&)> >(__gnu_cxx::__normal_iterator<Graphics::Render::RenderQueue::RenderQueueNode*, std::vector<Graphics::Render::RenderQueue::RenderQueueNode, std::allocator<Graphics::Render::RenderQueue::RenderQueueNode> > >, __gnu_cxx::__normal_iterator<Graphics::Render::RenderQueue::RenderQueueNode*, std::vector<Graphics::Render::RenderQueue::RenderQueueNode, std::allocator<Graphics::Render::RenderQueue::RenderQueueNode> > >, long, __gnu_cxx::__ops::_Iter_comp_iter<bool (*)(Graphics::Render::RenderQueue::RenderQueueNode const&, Graphics::Render::RenderQueue::RenderQueueNode const&)>) /usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/include/g++-v8/bits/stl_algo.h:1953
    #5 0x55a9cfd2a199 in void std::__sort<__gnu_cxx::__normal_iterator<Graphics::Render::RenderQueue::RenderQueueNode*, std::vector<Graphics::Render::RenderQueue::RenderQueueNode, std::allocator<Graphics::Render::RenderQueue::RenderQueueNode> > >, __gnu_cxx::__ops::_Iter_comp_iter<bool (*)(Graphics::Render::RenderQueue::RenderQueueNode const&, Graphics::Render::RenderQueue::RenderQueueNode const&)> >(__gnu_cxx::__normal_iterator<Graphics::Render::RenderQueue::RenderQueueNode*, std::vector<Graphics::Render::RenderQueue::RenderQueueNode, std::allocator<Graphics::Render::RenderQueue::RenderQueueNode> > >, __gnu_cxx::__normal_iterator<Graphics::Render::RenderQueue::RenderQueueNode*, std::vector<Graphics::Render::RenderQueue::RenderQueueNode, std::allocator<Graphics::Render::RenderQueue::RenderQueueNode> > >, __gnu_cxx::__ops::_Iter_comp_iter<bool (*)(Graphics::Render::RenderQueue::RenderQueueNode const&, Graphics::Render::RenderQueue::RenderQueueNode const&)>) /usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/include/g++-v8/bits/stl_algo.h:1968
    #6 0x55a9cfd2a199 in void std::sort<__gnu_cxx::__normal_iterator<Graphics::Render::RenderQueue::RenderQueueNode*, std::vector<Graphics::Render::RenderQueue::RenderQueueNode, std::allocator<Graphics::Render::RenderQueue::RenderQueueNode> > >, bool (*)(Graphics::Render::RenderQueue::RenderQueueNode const&, Graphics::Render::RenderQueue::RenderQueueNode const&)>(__gnu_cxx::__normal_iterator<Graphics::Render::RenderQueue::RenderQueueNode*, std::vector<Graphics::Render::RenderQueue::RenderQueueNode, std::allocator<Graphics::Render::RenderQueue::RenderQueueNode> > >, __gnu_cxx::__normal_iterator<Graphics::Render::RenderQueue::RenderQueueNode*, std::vector<Graphics::Render::RenderQueue::RenderQueueNode, std::allocator<Graphics::Render::RenderQueue::RenderQueueNode> > >, bool (*)(Graphics::Render::RenderQueue::RenderQueueNode const&, Graphics::Render::RenderQueue::RenderQueueNode const&)) /usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/include/g++-v8/bits/stl_algo.h:4866
    #7 0x55a9cfd2a199 in Graphics::Render::RenderQueue::sortDepth() /home/drmccoy/projects/xoreos/xoreos/src/graphics/render/renderqueue.cpp:100
    #8 0x55a9cfd214bc in Graphics::Render::RenderManager::sort() /home/drmccoy/projects/xoreos/xoreos/src/graphics/render/renderman.cpp:85
    #9 0x55a9cf664b30 in Graphics::GraphicsManager::renderWorldShader() /home/drmccoy/projects/xoreos/xoreos/src/graphics/graphics.cpp:1123
    #10 0x55a9cf666db6 in Graphics::GraphicsManager::renderScene() /home/drmccoy/projects/xoreos/xoreos/src/graphics/graphics.cpp:1233
    #11 0x55a9cf258ee8 in Events::EventsManager::runMainLoop() /home/drmccoy/projects/xoreos/xoreos/src/events/events.cpp:349
    #12 0x55a9ce22d0af in main /home/drmccoy/projects/xoreos/xoreos/src/xoreos.cpp:184
    #13 0x7f43ff05fae6 in __libc_start_main ../csu/libc-start.c:308
    #14 0x55a9ce243449 in _start (/mnt/ramdisk/xoreos/src/xoreos+0x4038449)

0x62e0000243f8 is located 8 bytes to the left of 48000-byte region [0x62e000024400,0x62e00002ff80)
allocated by thread T8 (GameInstance) here:
    #0 0x7f44033aa1c0 in operator new(unsigned long) /var/tmp/portage/sys-devel/gcc-8.2.0-r4/work/gcc-8.2.0/libsanitizer/asan/asan_new_delete.cc:90
    #1 0x55a9cfd22566 in __gnu_cxx::new_allocator<Graphics::Render::RenderQueue::RenderQueueNode>::allocate(unsigned long, void const*) /usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/include/g++-v8/ext/new_allocator.h:111
    #2 0x55a9cfd22566 in std::allocator_traits<std::allocator<Graphics::Render::RenderQueue::RenderQueueNode> >::allocate(std::allocator<Graphics::Render::RenderQueue::RenderQueueNode>&, unsigned long) /usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/include/g++-v8/bits/alloc_traits.h:436
    #3 0x55a9cfd22566 in std::_Vector_base<Graphics::Render::RenderQueue::RenderQueueNode, std::allocator<Graphics::Render::RenderQueue::RenderQueueNode> >::_M_allocate(unsigned long) /usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/include/g++-v8/bits/stl_vector.h:296
    #4 0x55a9cfd22566 in std::_Vector_base<Graphics::Render::RenderQueue::RenderQueueNode, std::allocator<Graphics::Render::RenderQueue::RenderQueueNode> >::_M_create_storage(unsigned long) /usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/include/g++-v8/bits/stl_vector.h:311
    #5 0x55a9cfd22566 in std::_Vector_base<Graphics::Render::RenderQueue::RenderQueueNode, std::allocator<Graphics::Render::RenderQueue::RenderQueueNode> >::_Vector_base(unsigned long, std::allocator<Graphics::Render::RenderQueue::RenderQueueNode> const&) /usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/include/g++-v8/bits/stl_vector.h:260
    #6 0x55a9cfd22566 in std::vector<Graphics::Render::RenderQueue::RenderQueueNode, std::allocator<Graphics::Render::RenderQueue::RenderQueueNode> >::vector(unsigned long, std::allocator<Graphics::Render::RenderQueue::RenderQueueNode> const&) /usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/include/g++-v8/bits/stl_vector.h:416
    #7 0x55a9cfd22566 in Graphics::Render::RenderQueue::RenderQueue(unsigned int) /home/drmccoy/projects/xoreos/xoreos/src/graphics/render/renderqueue.cpp:58
    #8 0x55a9cfd2073a in Graphics::Render::RenderManager::RenderManager() /home/drmccoy/projects/xoreos/xoreos/src/graphics/render/renderman.cpp:35
    #9 0x55a9ce602afc in Common::Singleton<Graphics::Render::RenderManager>::makeInstance() /home/drmccoy/projects/xoreos/xoreos/src/common/singleton.h:81
    #10 0x55a9ce602afc in Common::Singleton<Graphics::Render::RenderManager>::instance() /home/drmccoy/projects/xoreos/xoreos/src/common/singleton.h:100
    #11 0x55a9ce602afc in Engines::Jade::JadeEngine::init() /home/drmccoy/projects/xoreos/xoreos/src/engines/jade/jade.cpp:214
    #12 0x55a9ce6032b1 in Engines::Jade::JadeEngine::run() /home/drmccoy/projects/xoreos/xoreos/src/engines/jade/jade.cpp:156
    #13 0x55a9cf1082e6 in Engines::GameInstanceEngine::run() /home/drmccoy/projects/xoreos/xoreos/src/engines/enginemanager.cpp:225
    #14 0x55a9cf10a180 in Engines::EngineManager::run(Engines::GameInstance&) const /home/drmccoy/projects/xoreos/xoreos/src/engines/enginemanager.cpp:252
    #15 0x55a9cf10bb4b in Engines::GameThread::threadMethod() /home/drmccoy/projects/xoreos/xoreos/src/engines/gamethread.cpp:87
    #16 0x55a9d0289923 in Common::Thread::threadHelper(void*) /home/drmccoy/projects/xoreos/xoreos/src/common/thread.cpp:113
    #17 0x7f440419218b in SDL_RunThread /var/tmp/portage/media-libs/libsdl2-2.0.9/work/SDL2-2.0.9/src/thread/SDL_thread.c:283

Thread T8 (GameInstance) created by T0 here:
    #0 0x7f4403305b73 in __interceptor_pthread_create /var/tmp/portage/sys-devel/gcc-8.2.0-r4/work/gcc-8.2.0/libsanitizer/asan/asan_interceptors.cc:202
    #1 0x7f44041f9546 in SDL_SYS_CreateThread /var/tmp/portage/media-libs/libsdl2-2.0.9/work/SDL2-2.0.9/src/thread/pthread/SDL_systhread.c:119

SUMMARY: AddressSanitizer: heap-buffer-overflow /home/drmccoy/projects/xoreos/xoreos/src/graphics/render/renderqueue.cpp:54 in Graphics::Render::compareDepth(Graphics::Render::RenderQueue::RenderQueueNode const&, Graphics::Render::RenderQueue::RenderQueueNode const&)
Shadow bytes around the buggy address:
  0x0c5c7fffc820: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c5c7fffc830: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c5c7fffc840: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c5c7fffc850: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c5c7fffc860: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
=>0x0c5c7fffc870: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa[fa]
  0x0c5c7fffc880: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c5c7fffc890: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c5c7fffc8a0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c5c7fffc8b0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c5c7fffc8c0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==21108==ABORTING
```

**Comment by DrMcCoy** [comment]
The NWN fadequad also stopped working

**Comment by DrMcCoy** [comment]
Hej, any news on this, @seedhartha? :)

**Comment by seedhartha** [comment]
Hi! The last thing I did was trying to catch a leak in NWN from #381. No luck so far. When time allows I'd definitely try to get those fixes in.

**Comment by DrMcCoy** [comment]
Okay, thanks! :)

**Comment by seedhartha** [comment]
Reduced this PR to only implement shader-based skeletal animation. It should fix the issues above. Also, there was a regression in current master that broke experimental renderer for Jade Empire.

**Comment by DrMcCoy** [comment]
Okay, merged as 1ce3e31a1...b68e3b8f3, thanks! :)

Can you open a GitHub issue for the Jade Empire regression, please?

**Pull request closed without merging**
