### PR TITLE
JADE: Remove dependency on KotOR GUI

### PR DESCRIPTION
**Pull request by seedhartha**
Make Jade Empire use a copy of KotOR GUI, effectively removing the dependency on KotOR engine. This is the first step of the GUI system update I have in mind.

### CODE REVIEW

**Comment by Nostritius** [comment]
Just for clarification, where is the benefit in making an extra copy of the gui system for jade?

**Comment by seedhartha** [comment]
IMHO, KotOR and Jade are two separate contexts with different requirements and corner cases. This approach is also more in line with #261.

**Comment by Nostritius** [comment]
Then why not simply seperating the gui system from kotor and make it an external dependency, like for example the script engines? Because, from what i know about the jade gui system, it's pretty much the same as in kotor.

**Comment by DrMcCoy** [comment]
Is there a way we can find a common base the GUIs in the KotORs and Jade? No idea where that best fit, but maybe into src/engines/aurora/?

Likewise, I'd really like some common base for most of the two KotORs. Maybe through some kind of "virtual" engine?

**Comment by seedhartha** [comment]
Sure, it makes sense to extract the common base for KotOR games and Jade Empire. As I said, it is only the first step.

**Comment by DrMcCoy** [comment]
Merged as 8cf96010, thanks! :)

**Pull request closed without merging**
