### PR TITLE
NWN2: Add a Trigger class with a trap implementation

### PR DESCRIPTION
**Pull request by rjshae**
This pull request incorporates code changes to add the Trigger class for NWN2 and
embeds a new Trap class into the Door, Placeable, and Trigger classes. Detecting
and disabling traps requires skill checks; skills in turn depend on character feats, so
this adds in a partly-implemented Feats class. Traps can be detected but are not
triggered by a friendly faction, so a Factions class was implemented. For
completeness, personal reputation was included for the Factions class. Various small
details were included as needed, such as synergy skills and racial feats dependent on
area type. The types.h file was updated to include constants for the various 2da file
rows used.

Note that trap highlighting and cursor change for a trap mouse-over is not included
with this pull.

### CODE REVIEW

**Comment by rjshae** [comment]
All right, I'll have a look when I get a chance. I'm finishing up another project at the moment. Thanks.

**Comment by rjshae** [comment]
At the moment I'm stumped trying to address the memory leak. I changed this code:
`	Common::SeekableReadStream *stream = ResMan.getResource("repute", Aurora::kFileTypeFAC);
	if (!stream)
		throw Common::Exception("No repute.FAC available");
 	Aurora::GFF3File *gff = new Aurora::GFF3File(stream, MKTAG('F', 'A', 'C', ' '));`
to this:
`        Common::ScopedPtr<Common::SeekableReadStream> stream(ResMan.getResource("repute", Aurora::kFileTypeFAC));
        if (!stream)
                throw Common::Exception("No repute.FAC available");

        Common::ScopedPtr<Aurora::GFF3File> gff(new Aurora::GFF3File(&(*stream), MKTAG('F', 'A', 'C', ' ')));`
but I'm getting a segmentation fault. I've tried various other ways of re-writing the GFF3File call, but none of those compiled. Obviously there's something about the ScopedPtr construct I'm not getting.

**Comment by DrMcCoy** [comment]
(Hmmpf, apparently email replies don't do markdown. So ignore the
stray ``` in my reply, that was supposed to mark a code section)

**Comment by rjshae** [comment]
> Ah, yes. The thing is that GFF3File takes over the stream, and deletes it in its destructor. So when you have the stream in a ScopedPtr, you need to transfer ownership with release().

That resolved it. Thank you for your help.

**Comment by DrMcCoy** [comment]
Merged as 8b3fbd834...1fbce0525, thanks! :)

(I did meld the style and leak fixes into the original commits, though)

**Pull request closed without merging**
