### PR TITLE
AURORA: GFF3Writer Update

### PR DESCRIPTION
**Pull request by Nostritius**
This PR updates the GFF3Writer and some of it's components to reuse complex values and through that reduce the size of the generated Files. The original games are already doing that.

### CODE REVIEW

**Comment by DrMcCoy** [comment]
What the heck is happening there: https://ci.appveyor.com/project/DrMcCoy/xoreos/builds/23165421#L6689 :/

Looks like GFF3Writer.WriteNestedStructs is crashing? I see no sanitizer complaints on my machine, tho...

**Comment by Nostritius** [comment]
I have now found and fixed the bug, which caused the program to fail in appveyor. For anyone having a similar issue, the reason for that is, that msvc enforces strict weak ordering in std::map, with certain invariants. Is an invariant violated, the program will fail. I made thee < operators more strix to prevent as far as possible something like that for the future.

**Comment by DrMcCoy** [comment]
Oooh, interesting! Thanks for investigating and fixing this! :)

**Comment by Nostritius** [comment]
Now the c++11 bug in clang should also be solved.

**Comment by DrMcCoy** [comment]
Merged as 8e12d510d...5a16bf71e, thanks! :)

**Pull request closed without merging**
