### PR TITLE
WITCHER: Lua methods for main menu

### PR DESCRIPTION
**Pull request by Nostritius**
I took a look into the witcher gui, and the entry point to create the main menu (createMainMenuPanel). And tried to implement required lua methods as far as possible.

### CODE REVIEW

**Comment by DrMcCoy** [comment]
A few sanitizer complaints:

```
WARNING: TODO: Unimplemented Lua function "Quaternion:new_local()"!
/home/drmccoy/projects/xoreos/xoreos/lua/lfunc.cpp:44:13: runtime error: member access within null pointer of type 'union GCObject'
    #0 0x55c27f5a85e4 in luaF_findupval(lua_State*, lua_TObject*) /home/drmccoy/projects/xoreos/xoreos/lua/lfunc.cpp:44
    #1 0x55c27f5f485b in luaV_execute(lua_State*) /home/drmccoy/projects/xoreos/xoreos/lua/lvm.cpp:770
    #2 0x55c27f5a25b7 in luaD_call(lua_State*, lua_TObject*, int) /home/drmccoy/projects/xoreos/xoreos/lua/ldo.cpp:313
    #3 0x55c27f59a982 in luaD_rawrunprotected(lua_State*, void (*)(lua_State*, void*), void*) /home/drmccoy/projects/xoreos/xoreos/lua/ldo.cpp:88
    #4 0x55c27f5a3d38 in luaD_pcall(lua_State*, void (*)(lua_State*, void*), void*, long, long) /home/drmccoy/projects/xoreos/xoreos/lua/ldo.cpp:416
    #5 0x55c27f5879e8 in lua_pcall(lua_State*, int, int, int) /home/drmccoy/projects/xoreos/xoreos/lua/lapi.cpp:691
    #6 0x55c27f58dd80 in aux_do /home/drmccoy/projects/xoreos/xoreos/lua/lauxlib.cpp:569
    #7 0x55c27f58dd80 in lua_dobuffer(lua_State*, char const*, unsigned long, char const*) /home/drmccoy/projects/xoreos/xoreos/lua/lauxlib.cpp:583
    #8 0x55c27f0c3924 in Aurora::Lua::ScriptManager::executeFile(Common::UString const&) /home/drmccoy/projects/xoreos/xoreos/src/aurora/lua/scriptman.cpp:99
    #9 0x55c27f0c5011 in Aurora::Lua::ScriptManager::luaPlayFile(lua_State*) /home/drmccoy/projects/xoreos/xoreos/src/aurora/lua/scriptman.cpp:395
    #10 0x55c27f59d807 in luaD_precall(lua_State*, lua_TObject*) /home/drmccoy/projects/xoreos/xoreos/lua/ldo.cpp:260
    #11 0x55c27f5f2dc3 in luaV_execute(lua_State*) /home/drmccoy/projects/xoreos/xoreos/lua/lvm.cpp:627
    #12 0x55c27f5a25b7 in luaD_call(lua_State*, lua_TObject*, int) /home/drmccoy/projects/xoreos/xoreos/lua/ldo.cpp:313
    #13 0x55c27f59a982 in luaD_rawrunprotected(lua_State*, void (*)(lua_State*, void*), void*) /home/drmccoy/projects/xoreos/xoreos/lua/ldo.cpp:88
    #14 0x55c27f5a3d38 in luaD_pcall(lua_State*, void (*)(lua_State*, void*), void*, long, long) /home/drmccoy/projects/xoreos/xoreos/lua/ldo.cpp:416
    #15 0x55c27f5879e8 in lua_pcall(lua_State*, int, int, int) /home/drmccoy/projects/xoreos/xoreos/lua/lapi.cpp:691
    #16 0x55c27f58dd80 in aux_do /home/drmccoy/projects/xoreos/xoreos/lua/lauxlib.cpp:569
    #17 0x55c27f58dd80 in lua_dobuffer(lua_State*, char const*, unsigned long, char const*) /home/drmccoy/projects/xoreos/xoreos/lua/lauxlib.cpp:583
    #18 0x55c27f0c3924 in Aurora::Lua::ScriptManager::executeFile(Common::UString const&) /home/drmccoy/projects/xoreos/xoreos/src/aurora/lua/scriptman.cpp:99
    #19 0x55c27d409c09 in Engines::Witcher::Game::run() /home/drmccoy/projects/xoreos/xoreos/src/engines/witcher/game.cpp:88
    #20 0x55c27d3f35ad in Engines::Witcher::WitcherEngine::run() /home/drmccoy/projects/xoreos/xoreos/src/engines/witcher/witcher.cpp:154
    #21 0x55c27dff0446 in Engines::GameInstanceEngine::run() /home/drmccoy/projects/xoreos/xoreos/src/engines/enginemanager.cpp:225
    #22 0x55c27dff22e0 in Engines::EngineManager::run(Engines::GameInstance&) const /home/drmccoy/projects/xoreos/xoreos/src/engines/enginemanager.cpp:252
    #23 0x55c27dff3cab in Engines::GameThread::threadMethod() /home/drmccoy/projects/xoreos/xoreos/src/engines/gamethread.cpp:87
    #24 0x55c27f147d53 in Common::Thread::threadHelper(void*) /home/drmccoy/projects/xoreos/xoreos/src/common/thread.cpp:113
    #25 0x7f887befc18b in SDL_RunThread /var/tmp/portage/media-libs/libsdl2-2.0.9/work/SDL2-2.0.9/src/thread/SDL_thread.c:283
    #26 0x7f887bf63478 in RunThread /var/tmp/portage/media-libs/libsdl2-2.0.9/work/SDL2-2.0.9/src/thread/pthread/SDL_systhread.c:78
    #27 0x7f887ae029a9 in start_thread /var/tmp/portage/sys-libs/glibc-2.27-r6/work/glibc-2.27/nptl/pthread_create.c:463
    #28 0x7f8876a8756e in clone (/lib64/libc.so.6+0x10456e)

/home/drmccoy/projects/xoreos/xoreos/lua/lfunc.cpp:60:15: runtime error: member access within null pointer of type 'union GCObject'
    #0 0x55c27f5a8ad3 in luaF_close(lua_State*, lua_TObject*) /home/drmccoy/projects/xoreos/xoreos/lua/lfunc.cpp:60
    #1 0x55c27f5f2aff in luaV_execute(lua_State*) /home/drmccoy/projects/xoreos/xoreos/lua/lvm.cpp:668
    #2 0x55c27f5a25b7 in luaD_call(lua_State*, lua_TObject*, int) /home/drmccoy/projects/xoreos/xoreos/lua/ldo.cpp:313
    #3 0x55c27f59a982 in luaD_rawrunprotected(lua_State*, void (*)(lua_State*, void*), void*) /home/drmccoy/projects/xoreos/xoreos/lua/ldo.cpp:88
    #4 0x55c27f5a3d38 in luaD_pcall(lua_State*, void (*)(lua_State*, void*), void*, long, long) /home/drmccoy/projects/xoreos/xoreos/lua/ldo.cpp:416
    #5 0x55c27f5879e8 in lua_pcall(lua_State*, int, int, int) /home/drmccoy/projects/xoreos/xoreos/lua/lapi.cpp:691
    #6 0x55c27f58dd80 in aux_do /home/drmccoy/projects/xoreos/xoreos/lua/lauxlib.cpp:569
    #7 0x55c27f58dd80 in lua_dobuffer(lua_State*, char const*, unsigned long, char const*) /home/drmccoy/projects/xoreos/xoreos/lua/lauxlib.cpp:583
    #8 0x55c27f0c3924 in Aurora::Lua::ScriptManager::executeFile(Common::UString const&) /home/drmccoy/projects/xoreos/xoreos/src/aurora/lua/scriptman.cpp:99
    #9 0x55c27f0c5011 in Aurora::Lua::ScriptManager::luaPlayFile(lua_State*) /home/drmccoy/projects/xoreos/xoreos/src/aurora/lua/scriptman.cpp:395
    #10 0x55c27f59d807 in luaD_precall(lua_State*, lua_TObject*) /home/drmccoy/projects/xoreos/xoreos/lua/ldo.cpp:260
    #11 0x55c27f5f2dc3 in luaV_execute(lua_State*) /home/drmccoy/projects/xoreos/xoreos/lua/lvm.cpp:627
    #12 0x55c27f5a25b7 in luaD_call(lua_State*, lua_TObject*, int) /home/drmccoy/projects/xoreos/xoreos/lua/ldo.cpp:313
    #13 0x55c27f59a982 in luaD_rawrunprotected(lua_State*, void (*)(lua_State*, void*), void*) /home/drmccoy/projects/xoreos/xoreos/lua/ldo.cpp:88
    #14 0x55c27f5a3d38 in luaD_pcall(lua_State*, void (*)(lua_State*, void*), void*, long, long) /home/drmccoy/projects/xoreos/xoreos/lua/ldo.cpp:416
    #15 0x55c27f5879e8 in lua_pcall(lua_State*, int, int, int) /home/drmccoy/projects/xoreos/xoreos/lua/lapi.cpp:691
    #16 0x55c27f58dd80 in aux_do /home/drmccoy/projects/xoreos/xoreos/lua/lauxlib.cpp:569
    #17 0x55c27f58dd80 in lua_dobuffer(lua_State*, char const*, unsigned long, char const*) /home/drmccoy/projects/xoreos/xoreos/lua/lauxlib.cpp:583
    #18 0x55c27f0c3924 in Aurora::Lua::ScriptManager::executeFile(Common::UString const&) /home/drmccoy/projects/xoreos/xoreos/src/aurora/lua/scriptman.cpp:99
    #19 0x55c27d409c09 in Engines::Witcher::Game::run() /home/drmccoy/projects/xoreos/xoreos/src/engines/witcher/game.cpp:88
    #20 0x55c27d3f35ad in Engines::Witcher::WitcherEngine::run() /home/drmccoy/projects/xoreos/xoreos/src/engines/witcher/witcher.cpp:154
    #21 0x55c27dff0446 in Engines::GameInstanceEngine::run() /home/drmccoy/projects/xoreos/xoreos/src/engines/enginemanager.cpp:225
    #22 0x55c27dff22e0 in Engines::EngineManager::run(Engines::GameInstance&) const /home/drmccoy/projects/xoreos/xoreos/src/engines/enginemanager.cpp:252
    #23 0x55c27dff3cab in Engines::GameThread::threadMethod() /home/drmccoy/projects/xoreos/xoreos/src/engines/gamethread.cpp:87
    #24 0x55c27f147d53 in Common::Thread::threadHelper(void*) /home/drmccoy/projects/xoreos/xoreos/src/common/thread.cpp:113
    #25 0x7f887befc18b in SDL_RunThread /var/tmp/portage/media-libs/libsdl2-2.0.9/work/SDL2-2.0.9/src/thread/SDL_thread.c:283
    #26 0x7f887bf63478 in RunThread /var/tmp/portage/media-libs/libsdl2-2.0.9/work/SDL2-2.0.9/src/thread/pthread/SDL_systhread.c:78
    #27 0x7f887ae029a9 in start_thread /var/tmp/portage/sys-libs/glibc-2.27-r6/work/glibc-2.27/nptl/pthread_create.c:463
    #28 0x7f8876a8756e in clone (/lib64/libc.so.6+0x10456e)

WARNING: TODO: Unimplemented Lua function "Quaternion:new_local()"!
/home/drmccoy/projects/xoreos/xoreos/lua/lfunc.cpp:44:13: runtime error: member access within null pointer of type 'union GCObject'
    #0 0x55c27f5a8524 in luaF_findupval(lua_State*, lua_TObject*) /home/drmccoy/projects/xoreos/xoreos/lua/lfunc.cpp:44
    #1 0x55c27f5f485b in luaV_execute(lua_State*) /home/drmccoy/projects/xoreos/xoreos/lua/lvm.cpp:770
    #2 0x55c27f5a25b7 in luaD_call(lua_State*, lua_TObject*, int) /home/drmccoy/projects/xoreos/xoreos/lua/ldo.cpp:313
    #3 0x55c27f59a982 in luaD_rawrunprotected(lua_State*, void (*)(lua_State*, void*), void*) /home/drmccoy/projects/xoreos/xoreos/lua/ldo.cpp:88
    #4 0x55c27f5a3d38 in luaD_pcall(lua_State*, void (*)(lua_State*, void*), void*, long, long) /home/drmccoy/projects/xoreos/xoreos/lua/ldo.cpp:416
    #5 0x55c27f5879e8 in lua_pcall(lua_State*, int, int, int) /home/drmccoy/projects/xoreos/xoreos/lua/lapi.cpp:691
    #6 0x55c27f58dd80 in aux_do /home/drmccoy/projects/xoreos/xoreos/lua/lauxlib.cpp:569
    #7 0x55c27f58dd80 in lua_dobuffer(lua_State*, char const*, unsigned long, char const*) /home/drmccoy/projects/xoreos/xoreos/lua/lauxlib.cpp:583
    #8 0x55c27f0c3924 in Aurora::Lua::ScriptManager::executeFile(Common::UString const&) /home/drmccoy/projects/xoreos/xoreos/src/aurora/lua/scriptman.cpp:99
    #9 0x55c27f0c5011 in Aurora::Lua::ScriptManager::luaPlayFile(lua_State*) /home/drmccoy/projects/xoreos/xoreos/src/aurora/lua/scriptman.cpp:395
    #10 0x55c27f59d807 in luaD_precall(lua_State*, lua_TObject*) /home/drmccoy/projects/xoreos/xoreos/lua/ldo.cpp:260
    #11 0x55c27f5f2dc3 in luaV_execute(lua_State*) /home/drmccoy/projects/xoreos/xoreos/lua/lvm.cpp:627
    #12 0x55c27f5a25b7 in luaD_call(lua_State*, lua_TObject*, int) /home/drmccoy/projects/xoreos/xoreos/lua/ldo.cpp:313
    #13 0x55c27f59a982 in luaD_rawrunprotected(lua_State*, void (*)(lua_State*, void*), void*) /home/drmccoy/projects/xoreos/xoreos/lua/ldo.cpp:88
    #14 0x55c27f5a3d38 in luaD_pcall(lua_State*, void (*)(lua_State*, void*), void*, long, long) /home/drmccoy/projects/xoreos/xoreos/lua/ldo.cpp:416
    #15 0x55c27f5879e8 in lua_pcall(lua_State*, int, int, int) /home/drmccoy/projects/xoreos/xoreos/lua/lapi.cpp:691
    #16 0x55c27f58dd80 in aux_do /home/drmccoy/projects/xoreos/xoreos/lua/lauxlib.cpp:569
    #17 0x55c27f58dd80 in lua_dobuffer(lua_State*, char const*, unsigned long, char const*) /home/drmccoy/projects/xoreos/xoreos/lua/lauxlib.cpp:583
    #18 0x55c27f0c3924 in Aurora::Lua::ScriptManager::executeFile(Common::UString const&) /home/drmccoy/projects/xoreos/xoreos/src/aurora/lua/scriptman.cpp:99
    #19 0x55c27d409c09 in Engines::Witcher::Game::run() /home/drmccoy/projects/xoreos/xoreos/src/engines/witcher/game.cpp:88
    #20 0x55c27d3f35ad in Engines::Witcher::WitcherEngine::run() /home/drmccoy/projects/xoreos/xoreos/src/engines/witcher/witcher.cpp:154
    #21 0x55c27dff0446 in Engines::GameInstanceEngine::run() /home/drmccoy/projects/xoreos/xoreos/src/engines/enginemanager.cpp:225
    #22 0x55c27dff22e0 in Engines::EngineManager::run(Engines::GameInstance&) const /home/drmccoy/projects/xoreos/xoreos/src/engines/enginemanager.cpp:252
    #23 0x55c27dff3cab in Engines::GameThread::threadMethod() /home/drmccoy/projects/xoreos/xoreos/src/engines/gamethread.cpp:87
    #24 0x55c27f147d53 in Common::Thread::threadHelper(void*) /home/drmccoy/projects/xoreos/xoreos/src/common/thread.cpp:113
    #25 0x7f887befc18b in SDL_RunThread /var/tmp/portage/media-libs/libsdl2-2.0.9/work/SDL2-2.0.9/src/thread/SDL_thread.c:283
    #26 0x7f887bf63478 in RunThread /var/tmp/portage/media-libs/libsdl2-2.0.9/work/SDL2-2.0.9/src/thread/pthread/SDL_systhread.c:78
    #27 0x7f887ae029a9 in start_thread /var/tmp/portage/sys-libs/glibc-2.27-r6/work/glibc-2.27/nptl/pthread_create.c:463
    #28 0x7f8876a8756e in clone (/lib64/libc.so.6+0x10456e)

WARNING: TODO: Unimplemented Lua function "AurPrintf()"!
```

```
WARNING: TODO: void AddJournalEntry("Place", "kaer/basic")!
/home/drmccoy/projects/xoreos/xoreos/lua/lfunc.cpp:60:15: runtime error: member access within null pointer of type 'union GCObject'
    #0 0x55c27f5a8d48 in luaF_close(lua_State*, lua_TObject*) /home/drmccoy/projects/xoreos/xoreos/lua/lfunc.cpp:60
    #1 0x55c27f5a3ded in luaD_pcall(lua_State*, void (*)(lua_State*, void*), void*, long, long) /home/drmccoy/projects/xoreos/xoreos/lua/ldo.cpp:419
    #2 0x55c27f5879e8 in lua_pcall(lua_State*, int, int, int) /home/drmccoy/projects/xoreos/xoreos/lua/lapi.cpp:691
    #3 0x55c27f58dd80 in aux_do /home/drmccoy/projects/xoreos/xoreos/lua/lauxlib.cpp:569
    #4 0x55c27f58dd80 in lua_dobuffer(lua_State*, char const*, unsigned long, char const*) /home/drmccoy/projects/xoreos/xoreos/lua/lauxlib.cpp:583
    #5 0x55c27f0bfa2b in Aurora::Lua::ScriptManager::executeString(Common::UString const&) /home/drmccoy/projects/xoreos/xoreos/src/aurora/lua/scriptman.cpp:109
    #6 0x55c27d47f19a in Engines::Witcher::Functions::runClientLua(Aurora::NWScript::FunctionContext&) /home/drmccoy/projects/xoreos/xoreos/src/engines/witcher/nwscript/functions.cpp:105
    #7 0x55c27d482cf2 in boost::_mfi::mf1<void, Engines::Witcher::Functions, Aurora::NWScript::FunctionContext&>::operator()(Engines::Witcher::Functions*, Aurora::NWScript::FunctionContext&) const /usr/include/boost/bind/mem_fn_template.hpp:165
    #8 0x55c27d482cf2 in void boost::_bi::list2<boost::_bi::value<Engines::Witcher::Functions*>, boost::arg<1> >::operator()<boost::_mfi::mf1<void, Engines::Witcher::Functions, Aurora::NWScript::FunctionContext&>, boost::_bi::rrlist1<Aurora::NWScript::FunctionContext&> >(boost::_bi::type<void>, boost::_mfi::mf1<void, Engines::Witcher::Functions, Aurora::NWScript::FunctionContext&>&, boost::_bi::rrlist1<Aurora::NWScript::FunctionContext&>&, int) /usr/include/boost/bind/bind.hpp:319
    #9 0x55c27d482cf2 in void boost::_bi::bind_t<void, boost::_mfi::mf1<void, Engines::Witcher::Functions, Aurora::NWScript::FunctionContext&>, boost::_bi::list2<boost::_bi::value<Engines::Witcher::Functions*>, boost::arg<1> > >::operator()<Aurora::NWScript::FunctionContext&>(Aurora::NWScript::FunctionContext&) /usr/include/boost/bind/bind.hpp:1306
    #10 0x55c27d482cf2 in boost::detail::function::void_function_obj_invoker1<boost::_bi::bind_t<void, boost::_mfi::mf1<void, Engines::Witcher::Functions, Aurora::NWScript::FunctionContext&>, boost::_bi::list2<boost::_bi::value<Engines::Witcher::Functions*>, boost::arg<1> > >, void, Aurora::NWScript::FunctionContext&>::invoke(boost::detail::function::function_buffer&, Aurora::NWScript::FunctionContext&) /usr/include/boost/function/function_template.hpp:159
    #11 0x55c27f01b7e9 in boost::function1<void, Aurora::NWScript::FunctionContext&>::operator()(Aurora::NWScript::FunctionContext&) const /usr/include/boost/function/function_template.hpp:759
    #12 0x55c27f01b7e9 in Aurora::NWScript::FunctionManager::call(unsigned int, Aurora::NWScript::FunctionContext&) const /home/drmccoy/projects/xoreos/xoreos/src/aurora/nwscript/functionman.cpp:109
    #13 0x55c27f05eab0 in Aurora::NWScript::NCSFile::callEngine(Aurora::NWScript::FunctionContext&, unsigned int, unsigned char) /home/drmccoy/projects/xoreos/xoreos/src/aurora/nwscript/ncsfile.cpp:588
    #14 0x55c27f05ffd9 in Aurora::NWScript::NCSFile::o_action(Aurora::NWScript::NCSFile::InstructionType) /home/drmccoy/projects/xoreos/xoreos/src/aurora/nwscript/ncsfile.cpp:635
    #15 0x55c27f039e6c in Aurora::NWScript::NCSFile::executeStep() /home/drmccoy/projects/xoreos/xoreos/src/aurora/nwscript/ncsfile.cpp:419
    #16 0x55c27f03bb79 in Aurora::NWScript::NCSFile::execute(Aurora::NWScript::ObjectReference, Aurora::NWScript::ObjectReference) /home/drmccoy/projects/xoreos/xoreos/src/aurora/nwscript/ncsfile.cpp:388
    #17 0x55c27f043cb4 in Aurora::NWScript::NCSFile::run(Aurora::NWScript::ScriptState const&, Aurora::NWScript::ObjectReference, Aurora::NWScript::ObjectReference) /home/drmccoy/projects/xoreos/xoreos/src/aurora/nwscript/ncsfile.cpp:381
    #18 0x55c27f0447cd in Aurora::NWScript::NCSFile::run(Aurora::NWScript::Object*, Aurora::NWScript::Object*) /home/drmccoy/projects/xoreos/xoreos/src/aurora/nwscript/ncsfile.cpp:351
    #19 0x55c27d49fef5 in Engines::Witcher::Functions::executeScript(Aurora::NWScript::FunctionContext&) /home/drmccoy/projects/xoreos/xoreos/src/engines/witcher/nwscript/functions_action.cpp:87
    #20 0x55c27d482cf2 in boost::_mfi::mf1<void, Engines::Witcher::Functions, Aurora::NWScript::FunctionContext&>::operator()(Engines::Witcher::Functions*, Aurora::NWScript::FunctionContext&) const /usr/include/boost/bind/mem_fn_template.hpp:165
    #21 0x55c27d482cf2 in void boost::_bi::list2<boost::_bi::value<Engines::Witcher::Functions*>, boost::arg<1> >::operator()<boost::_mfi::mf1<void, Engines::Witcher::Functions, Aurora::NWScript::FunctionContext&>, boost::_bi::rrlist1<Aurora::NWScript::FunctionContext&> >(boost::_bi::type<void>, boost::_mfi::mf1<void, Engines::Witcher::Functions, Aurora::NWScript::FunctionContext&>&, boost::_bi::rrlist1<Aurora::NWScript::FunctionContext&>&, int) /usr/include/boost/bind/bind.hpp:319
    #22 0x55c27d482cf2 in void boost::_bi::bind_t<void, boost::_mfi::mf1<void, Engines::Witcher::Functions, Aurora::NWScript::FunctionContext&>, boost::_bi::list2<boost::_bi::value<Engines::Witcher::Functions*>, boost::arg<1> > >::operator()<Aurora::NWScript::FunctionContext&>(Aurora::NWScript::FunctionContext&) /usr/include/boost/bind/bind.hpp:1306
    #23 0x55c27d482cf2 in boost::detail::function::void_function_obj_invoker1<boost::_bi::bind_t<void, boost::_mfi::mf1<void, Engines::Witcher::Functions, Aurora::NWScript::FunctionContext&>, boost::_bi::list2<boost::_bi::value<Engines::Witcher::Functions*>, boost::arg<1> > >, void, Aurora::NWScript::FunctionContext&>::invoke(boost::detail::function::function_buffer&, Aurora::NWScript::FunctionContext&) /usr/include/boost/function/function_template.hpp:159
    #24 0x55c27f01b7e9 in boost::function1<void, Aurora::NWScript::FunctionContext&>::operator()(Aurora::NWScript::FunctionContext&) const /usr/include/boost/function/function_template.hpp:759
    #25 0x55c27f01b7e9 in Aurora::NWScript::FunctionManager::call(unsigned int, Aurora::NWScript::FunctionContext&) const /home/drmccoy/projects/xoreos/xoreos/src/aurora/nwscript/functionman.cpp:109
    #26 0x55c27f05eab0 in Aurora::NWScript::NCSFile::callEngine(Aurora::NWScript::FunctionContext&, unsigned int, unsigned char) /home/drmccoy/projects/xoreos/xoreos/src/aurora/nwscript/ncsfile.cpp:588
    #27 0x55c27f05ffd9 in Aurora::NWScript::NCSFile::o_action(Aurora::NWScript::NCSFile::InstructionType) /home/drmccoy/projects/xoreos/xoreos/src/aurora/nwscript/ncsfile.cpp:635
    #28 0x55c27f039e6c in Aurora::NWScript::NCSFile::executeStep() /home/drmccoy/projects/xoreos/xoreos/src/aurora/nwscript/ncsfile.cpp:419
    #29 0x55c27f03bb79 in Aurora::NWScript::NCSFile::execute(Aurora::NWScript::ObjectReference, Aurora::NWScript::ObjectReference) /home/drmccoy/projects/xoreos/xoreos/src/aurora/nwscript/ncsfile.cpp:388
    #30 0x55c27f043cb4 in Aurora::NWScript::NCSFile::run(Aurora::NWScript::ScriptState const&, Aurora::NWScript::ObjectReference, Aurora::NWScript::ObjectReference) /home/drmccoy/projects/xoreos/xoreos/src/aurora/nwscript/ncsfile.cpp:381
    #31 0x55c27d47e543 in Engines::Witcher::ScriptContainer::runScript(Common::UString const&, Aurora::NWScript::ScriptState const&, Aurora::NWScript::ObjectReference, Aurora::NWScript::ObjectReference) /home/drmccoy/projects/xoreos/xoreos/src/engines/witcher/nwscript/container.cpp:168
    #32 0x55c27d47e7bd in Engines::Witcher::ScriptContainer::runScript(Common::UString const&, Aurora::NWScript::ObjectReference, Aurora::NWScript::ObjectReference) /home/drmccoy/projects/xoreos/xoreos/src/engines/witcher/nwscript/container.cpp:155
    #33 0x55c27d42c1e6 in Engines::Witcher::Module::enterArea() /home/drmccoy/projects/xoreos/xoreos/src/engines/witcher/module.cpp:319
    #34 0x55c27d4345bb in Engines::Witcher::Module::processEventQueue() /home/drmccoy/projects/xoreos/xoreos/src/engines/witcher/module.cpp:277
    #35 0x55c27d4140c5 in Engines::Witcher::Campaign::handleEvents() /home/drmccoy/projects/xoreos/xoreos/src/engines/witcher/campaign.cpp:300
    #36 0x55c27d40888d in Engines::Witcher::Game::runCampaign() /home/drmccoy/projects/xoreos/xoreos/src/engines/witcher/game.cpp:114
    #37 0x55c27d409d08 in Engines::Witcher::Game::run() /home/drmccoy/projects/xoreos/xoreos/src/engines/witcher/game.cpp:91
    #38 0x55c27d3f35ad in Engines::Witcher::WitcherEngine::run() /home/drmccoy/projects/xoreos/xoreos/src/engines/witcher/witcher.cpp:154
    #39 0x55c27dff0446 in Engines::GameInstanceEngine::run() /home/drmccoy/projects/xoreos/xoreos/src/engines/enginemanager.cpp:225
    #40 0x55c27dff22e0 in Engines::EngineManager::run(Engines::GameInstance&) const /home/drmccoy/projects/xoreos/xoreos/src/engines/enginemanager.cpp:252
    #41 0x55c27dff3cab in Engines::GameThread::threadMethod() /home/drmccoy/projects/xoreos/xoreos/src/engines/gamethread.cpp:87
    #42 0x55c27f147d53 in Common::Thread::threadHelper(void*) /home/drmccoy/projects/xoreos/xoreos/src/common/thread.cpp:113
    #43 0x7f887befc18b in SDL_RunThread /var/tmp/portage/media-libs/libsdl2-2.0.9/work/SDL2-2.0.9/src/thread/SDL_thread.c:283
    #44 0x7f887bf63478 in RunThread /var/tmp/portage/media-libs/libsdl2-2.0.9/work/SDL2-2.0.9/src/thread/pthread/SDL_systhread.c:78
    #45 0x7f887ae029a9 in start_thread /var/tmp/portage/sys-libs/glibc-2.27-r6/work/glibc-2.27/nptl/pthread_create.c:463
    #46 0x7f8876a8756e in clone (/lib64/libc.so.6+0x10456e)

[string "g_GuiInGame:SetIconVisibility('Equipment', ..."]:1: attempt to index global `g_GuiInGame' (a nil value)
WARNING: Failed ExecuteScript("dis_all_panels", "Wiedzmin")
    Because: Failed running engine function "RunClientLua" (722)
    Because: Failed to execute Lua code: g_GuiInGame:SetIconVisibility('Equipment', true)
WARNING: TODO: int PreloadCreature("eskel_q1_1", <object>("l08"))!
```

(
There's also this, which has been there for a while:

```
/home/drmccoy/projects/xoreos/xoreos/lua/ltable.cpp:332:18: runtime error: member access within misaligned address 0xbebebebebebebebe for type 'union GCObject', which requires 8 byte alignment
0xbebebebebebebebe: note: pointer points here
<memory cannot be printed>
    #0 0x55c27f5dfd31 in luaH_new(lua_State*, int, int) /home/drmccoy/projects/xoreos/xoreos/lua/ltable.cpp:332
    #1 0x55c27f5d16b7 in f_luaopen /home/drmccoy/projects/xoreos/xoreos/lua/lstate.cpp:114
    #2 0x55c27f59a982 in luaD_rawrunprotected(lua_State*, void (*)(lua_State*, void*), void*) /home/drmccoy/projects/xoreos/xoreos/lua/ldo.cpp:88
    #3 0x55c27f5d3413 in lua_open() /home/drmccoy/projects/xoreos/xoreos/lua/lstate.cpp:189
    #4 0x55c27f0ca1c2 in Aurora::Lua::ScriptManager::openLuaState() /home/drmccoy/projects/xoreos/xoreos/src/aurora/lua/scriptman.cpp:297
    #5 0x55c27f0cc9f6 in Aurora::Lua::ScriptManager::init() /home/drmccoy/projects/xoreos/xoreos/src/aurora/lua/scriptman.cpp:63
    #6 0x55c27d3f292c in Engines::Witcher::WitcherEngine::init() /home/drmccoy/projects/xoreos/xoreos/src/engines/witcher/witcher.cpp:188
    #7 0x55c27d3f2fa1 in Engines::Witcher::WitcherEngine::run() /home/drmccoy/projects/xoreos/xoreos/src/engines/witcher/witcher.cpp:140
    #8 0x55c27dff0446 in Engines::GameInstanceEngine::run() /home/drmccoy/projects/xoreos/xoreos/src/engines/enginemanager.cpp:225
    #9 0x55c27dff22e0 in Engines::EngineManager::run(Engines::GameInstance&) const /home/drmccoy/projects/xoreos/xoreos/src/engines/enginemanager.cpp:252
    #10 0x55c27dff3cab in Engines::GameThread::threadMethod() /home/drmccoy/projects/xoreos/xoreos/src/engines/gamethread.cpp:87
    #11 0x55c27f147d53 in Common::Thread::threadHelper(void*) /home/drmccoy/projects/xoreos/xoreos/src/common/thread.cpp:113
    #12 0x7f887befc18b in SDL_RunThread /var/tmp/portage/media-libs/libsdl2-2.0.9/work/SDL2-2.0.9/src/thread/SDL_thread.c:283
    #13 0x7f887bf63478 in RunThread /var/tmp/portage/media-libs/libsdl2-2.0.9/work/SDL2-2.0.9/src/thread/pthread/SDL_systhread.c:78
    #14 0x7f887ae029a9 in start_thread /var/tmp/portage/sys-libs/glibc-2.27-r6/work/glibc-2.27/nptl/pthread_create.c:463
    #15 0x7f8876a8756e in clone (/lib64/libc.so.6+0x10456e)
```
)

**Comment by Nostritius** [comment]
How exactly can i reproduce the sanitizer outputs?

**Comment by DrMcCoy** [comment]
I use this script to (re)compile xoreos with the sanitizers enabled: https://gist.github.com/DrMcCoy/7ef8bc4fa83d49dbc84871e3f5ee03aa. You need to run that in the xoreos repository, For out-of-tree builds, you need to change the paths, of course.

Starting xoreos with such a build gives some information, but not full stack traces. There's two options you can set before running the executable, each one enabling more output but making the program run slower.

I have two more scripts for that: https://gist.github.com/DrMcCoy/1ff60fdfdc5201b75599ab5aabe795b0 and https://gist.github.com/DrMcCoy/a7591e5884b6a4258ec150372a9db61b. Since they call their arguments, you'd just them like this: `./sancheck.sh /path/to/xoreos`.

Alternatively, you can look at what the scripts do and just set the env vars yourself :P

**Comment by Nostritius** [comment]
Hmm, I've tested sanitizers in the master branch, and it seems, these problems were there before i changed anything.

**Comment by DrMcCoy** [comment]
Thanks :)

**Comment by DrMcCoy** [comment]
Merged as 71d16f084...8b3fbd834, thanks! :)

**Pull request closed without merging**
