### PR TITLE
VIDEOS: Fix quicktime compilation without libfaad

### PR DESCRIPTION
**Pull request by Nostritius**
I recognized, that a compilation error was thrown with the latest revision, when building without libfaad. This should fix it.

### CODE REVIEW

**Comment by DrMcCoy** [comment]
That commit is not really completely correct, though, is it?

I don't know much about Quicktime (that's @clone2727's forte :P), but it looks to me like it should rather go inside the 0x40 case, because the other cases might be something else.

There probably shouldn't be a `warning()` either, because that's not going to be triggered: `isAudioCodecSupported()` presumably already guards against `createAudioStream()` being called in that case. So it's only about removing the call to the removed function.

So I think it should rather be like this:

```c++
case MKTAG('m', 'p', '4', 'a'):
	switch (_objectTypeMP4) {
	case 0x40:
#ifdef ENABLE_FAAD
		return Sound::makeAACStream(*_extraData);
#else
		return 0;
#endif
	}
	break;
}
```

Does that make sense?

**Comment by clone2727** [comment]
@DrMcCoy is correct on all counts.

**Comment by Nostritius** [comment]
It should now be fixed

**Comment by DrMcCoy** [comment]
Okay, merged it as 92f92f896, then, thanks! :)

**Pull request closed without merging**
