### PR TITLE
AURORA: Add a loader for TheWitcherSave files

### PR DESCRIPTION
**Pull request by Nostritius**
The PR implements a  loader for .TheWitcherSave files

### CODE REVIEW

**Comment by DrMcCoy** [comment]
Neat, thanks :)

Can you add a small unit test as well, or do you feel you know too little yet?

**Comment by DrMcCoy** [comment]
I actually cheated and crafted them by hand.

So yeah, they're "validated" against my understanding of the format, and not necessarily an objective "official" version of the format. It will still find regressions in the code, though.

**Comment by Nostritius** [comment]
I have now added a unit test.

**Comment by Nostritius** [comment]
The style issues should now be corrected

**Comment by DrMcCoy** [comment]
Merged as 467c1e562...2375eba6d, thanks! :)

**Pull request closed without merging**
