### PR TITLE
MAIN: add counter to EventsManager::keyRepeat

### PR DESCRIPTION
**Pull request by Koffeinfriedhof**
add counter to EventsManager::keyRepeat

https://github.com/xoreos/xoreos/issues/99
Make keyboard states recursive/re-entrant

### CODE REVIEW

**Comment by DrMcCoy** [comment]
The subsystem for this should be "EVENTS", not "MAIN", and you should capitalize the first letter after the subsystem. I.e. "EVENTS: Add" instead of "MAIN: add".

**Comment by DrMcCoy** [comment]
If you can, consider configuring your IDE to show whitespace, or at least of the trailing kind, so you can catch it more easily.

**Comment by DrMcCoy** [comment]
You don't *have* to close the PR or delete the branch. You can just rebase the branch, and force-push it to GitHub, to automatically update the PR. :)

**Comment by Koffeinfriedhof** [comment]
Sorry. I used git reset to edit the issues...

**Pull request closed without merging**
