### PR TITLE
ACTIONSCRIPT: Update

### PR DESCRIPTION
**Pull request by Nostritius**
Another actionscript update, which now enables to fully execute the initialization sequence from the dragonage origins main menu.

### CODE REVIEW

**Comment by DrMcCoy** [comment]
(In case you haven't seen it, the unit tests don't link with this PR)

**Comment by Nostritius** [comment]
Yes, i have recognized this. I need to rethink my approach for the Stage class, since aurora shouldnt link to graphics for just one class

**Comment by DrMcCoy** [comment]
Okay, thanks :)

**Comment by Nostritius** [comment]
Ok, I have now removed the dependency to graphics. It should work now.

**Comment by DrMcCoy** [comment]
Merged as 4439bdc11...8bb133f4c, thanks! :)

**Pull request closed without merging**
