### PR TITLE
TRAVIS: Use Ninja when building with CMake

### PR DESCRIPTION
**Pull request by ccawley2011**
This should help reduce the build times when building with CMake.

### CODE REVIEW

**Comment by DrMcCoy** [comment]
(The problem we have right now is with the Coverity Scan builds, which don't use CMake at the moment. So I guess that would need to be changed to use CMake, too.)

**Comment by ccawley2011** [comment]
Compared to the last few builds, Ninja on Linux seems to save up to 2 minutes, while on Mac OS X it doesn't seem to have made much difference.

Regarding Coverity Scan, it might be worth using CMake regardless of this PR being merged since it appears to be substantially faster than autotools (almost 15 minutes faster in this case).

There are other possibilities that might also make a difference, such as using ccache, but those are things I'll investigate separately.

**Comment by DrMcCoy** [comment]
Yeah, but with ccache, you have to store the cache somewhere, and that makes it more difficult again. And that still means it'll have to run through at least once. And a new Coverity Scan release might invalidate the whole cache.

I really wonder why the build time has increased that much since the last Coverity Scan build. https://travis-ci.org/xoreos/xoreos/builds/474114774 ran through in 38 minutes, and now it's not even finished with the Jade engine (let alone all the unit tests) after 50 minutes.

**Comment by DrMcCoy** [comment]
Anyway, merged the Ninja set as 4c2b8a9, thanks! :)

Also enabled that for the Coverity Scan builds. Not tested yet, though, so we'll see if I broke it. :P

Additionally, someone from Travis CI got back to me and they did up the build time limit for xoreos. Still, in the long run, we should probably look into getting the build times down as well. Probably by decreasing includes, increasing forward-declarations?

**Comment by DrMcCoy** [comment]
With Ninja and CMake, the Coverity Scan build now takes 57 minutes.

CMake "breaks" the automatic Coverity Scan version tagging, though, because I'm grepping the Makefile for PACKAGE_VERSION for that. Our CMakeLists.txt isn't even setting these PACKAGE_ variables correctly; I probably should fix that.

**Comment by DrMcCoy** [comment]
Looking into the git log, we did switch to C++11 during the Coverity Scan downtime, so that might actually be the culprit. That's pretty wild.

**Pull request closed without merging**
