### PR TITLE
COMMON: Restore SDL based Semaphore class

### PR DESCRIPTION
**Pull request by seedhartha**
This fixes deadlock with anti-aliasing enabled.

### CODE REVIEW

**Comment by DrMcCoy** [comment]
Hmm, I thought the mutex + condition_variable basically is a semaphore?

I'm too tired right now to really thing it through, but IIRC this was the StackOverflow thread I read about it back then? https://stackoverflow.com/questions/4792449/c0x-has-no-semaphores-how-to-synchronize-threads

**Comment by seedhartha** [comment]
Correct. However, semaphore is a particular system object in Windows and Linux (SDL uses that). It is also a concept of its own, which we currently do not implement in our code.

**Comment by seedhartha** [comment]
As a side note, I believe it was a bad idea to switch to C++11 threads after all: there were definitely some performance and compatibility losses.

**Comment by DrMcCoy** [comment]
Hmm, okay, that is a bit disappointing. I had hoped moving to C++11 threads would *increase* performance and compatibility. :/

**Comment by DrMcCoy** [comment]
Merged, thanks :)

**Pull request merged**
