### PR TITLE
JADE: Add main menu

### PR DESCRIPTION
**Pull request by Nostritius**
I added the buttons for the MainMenu class and modified parts to scale with non-640x480 screens. Also I added some other things mostly related to the KotOR widgets which helped me building this. Be aware, that the MainMenu only scales correctly in 640x480 resolutions

### CODE REVIEW

**Comment by DrMcCoy** [comment]
Merged it as 75c923a19, thanks! :)

**Comment by DrMcCoy** [comment]
Ooops, sorry, I mistakingly closed those PR instead of #179. My bad.

**Comment by Nostritius** [comment]
This issues should now be solved

**Comment by DrMcCoy** [comment]
Merged it as 4e5b71ab7...ddf249c4d, thanks! :)

**Pull request closed without merging**
