### PR TITLE
DRAGONAGE2: Implement DoAreaTransition nwscript method

### PR DESCRIPTION
**Pull request by Nostritius**
This PR should make sure, that the default area loads the actual start area.

### CODE REVIEW

**Comment by DrMcCoy** [comment]
Huh, second parameter is a script? Are you sure?

My DA2 script.ldf says:
```
/** @brief Moves the entire party into an area
*
* This function will do an area transtion if the target area is within the same area·
* list of the current area OR if the target area is in a different area list then
* it will unload the current area list and load into memory (with a loading bar)
* a new area list. The party will then be jumped to the specified waypoint (if it exists)
*
* @param sArea - tag of the target area
* @param sWaypointTag - tag of the target waypoint
* @returns 1 for success, 0 for failure (area list does not exist or area does not exist)
* @remarks this function will jump ALL party members
* @author Ross
*/
int DoAreaTransition( string sArea, string sWaypointTag ) = 745;
```

I.e. the second parameter should be a waypoint to jump to, not a script.

**Comment by DrMcCoy** [comment]
Also, why are the gallows loaded at all anyways at the start? Is that the intro cutscene with Varric being interrogated?

**Comment by Nostritius** [comment]
I corrected the the waypoint parameter. About the gallows, i'm as confused about this as you are. Maybe the varric cutscene takes place somewhere there? But since it is explicitly marked as entry area, i suppose we should leave it for now.

**Comment by DrMcCoy** [comment]
Merged as d232ae1d0042aa405298263ca8d4fee150776b10, thanks! :)

**Pull request closed without merging**
