### PR TITLE
KotOR actions update

### PR DESCRIPTION
**Pull request by seedhartha**
This PR:
1. Extracts action execution to a dedicated class.
2. Implements collision detection for non-PC creatures.
3. Adds support for action "follow leader".
4. Loads creature speed based on appearance.

### CODE REVIEW

**Comment by DrMcCoy** [comment]
With this PR, Trask's movement is now framerate dependant. His animation is "jittering"/stuttering  with vsync turned on, walking smooth when vsync is turned off.

776b98cca seems to introduce this.

**Comment by seedhartha** [comment]
Fixed. There's also an issue with walk/run animation switch, though I believe it should be fixed with proper animation interpolation later.

**Comment by DrMcCoy** [comment]
Thanks :)

I'll recheck this later in the evening today. I'm currently not at home on my desktop, but on my laptop, and vsync doesn't work on my laptop [*], so I can't actually check this here.

[*] Nvidia with Optimus on Linux, which funnels the rendered image from the Nvidia memory into the in-CPU Intel GPU memory (and only the Intel GPU has access to the monitor). There is a way to make vsync work for that, but I'd need to rewrite my X config, and so far I haven't had time for that.

Though I might try getting the framerate down differently? Hmm...

**Comment by DrMcCoy** [comment]
Okay, checked with my desktop machine as well. And yes, the stuttering seems to be gone, nice, thanks! :)

Merged as e3c8c96de...169a42676

**Pull request closed without merging**
