### PR TITLE
BUILD: Fix cmake option() Boost_USE_STATIC_LIBS

### PR DESCRIPTION
**Pull request by kevL**

### CODE REVIEW

**Comment by DrMcCoy** [comment]
Merged, thanks! :)

**Comment by kevL** [comment]
/coffee, np

yeh i'm pluggin' away at it. Am done the cmake-hook (unique to my system but could be generally adapted, for MinGW builds someday). I upgraded to MinGW-w64(32-bit) + MSYS2. CMake3 has a few policy changes & whatnot that probly shouldn't be trusted with cmake_minimum_required(VERSION 2).

Am going to try bypassing/converting the automake files -> cmake files, today.


Here's the commandline i had to use to get through the repo's CMakeLists.txt w/out error:

cmake -G "MSYS Makefiles" ^
-DBOOST_ROOT="c:/msys32/mingw32" ^
-DSDL2_INCLUDE_DIR="c:/msys32/mingw32/include/SDL2" ^
-DSDL2_LIBRARY="c:/msys32/mingw32/lib/libSDL2.dll.a" ^
-DOPENAL_INCLUDE_DIR="c:/msys32/mingw32/include" ^
-DFREETYPE_INCLUDE_DIRS="c:/msys32/mingw32/include/freetype2" ^
-DFREETYPE_LIBRARY="c:/msys32/mingw32/lib/libfreetype.dll.a" ^
-DMAD_INCLUDE_DIR="c:/msys32/mingw32/include" ^
-DMAD_LIBRARY="c:/msys32/mingw32/lib/libmad.dll.a" ^
-DFAAD_INCLUDE_DIR="c:/msys32/mingw32/include" ^
-DFAAD_LIBRARY="c:/msys32/mingw32/lib/libfaad.dll.a" ^
-DOGG_INCLUDE_DIR="c:/msys32/mingw32/include" ^
-DOGG_LIBRARY="c:/msys32/mingw32/lib/libogg.dll.a" ^
-DVORBIS_INCLUDE_DIR="c:/msys32/mingw32/include/vorbis" ^
-DVORBIS_LIBRARY="c:/msys32/mingw32/lib/libvorbis.dll.a" ^
-DXVID_INCLUDE_DIR="c:/msys32/mingw32/include" ^
-DXVID_LIBRARY="c:/msys32/mingw32/lib/xvidcore.dll.a" ^
-DLIBLZMA_INCLUDE_DIR="c:/msys32/mingw32/include" ^
-DLIBLZMA_LIBRARY="c:/msys32/mingw32/lib/liblzma.dll.a" ^
-DLIBXML2_INCLUDE_DIR="c:/msys32/mingw32/include/libxml2/libxml" ^
-DLIBXML2_LIBRARIES="c:/msys32/mingw32/lib/libxml2.dll.a" ^
-DICONV_INCLUDE_DIR="c:/msys32/mingw32/include" ^
-DICONV_LIBRARIES="c:/msys32/mingw32/lib/libiconv.dll.a" ^
-DGLEW_INCLUDE_DIR="c:/msys32/mingw32/include" ^
-DGLEW_LIBRARY="c:/msys32/mingw32/lib/libglew32.dll.a" ^
.

<g>

Then, 'make' built a dozen or two .obj files and konked ... lul

oh Ps @ GIT: ended up deleting/cloning/mirroring my fork to get a clean tree. There seemed to be something deeply funky going on, once i switched to a git-commandline and saw some detail; even --force on dry-runs seemed to be refusing to work on branches in various ways. Looks good now,

**Comment by berenm** [comment]
If you want to build under MinGW/MSYS, you should run the CMake under your MinGW/MSYS bash environment, and CMake should be able to automatically detect the correct MinGW/MSYS fake root as well as the include dirs and libraries by itself.

I cannot confirm it ATM as I don't have access to Windows computer, but I'm 75% sure. Could you please paste the CMake log if you encounter any trouble?

**Comment by kevL** [comment]
hey beren,

|run cmake under bash
yeh i probly should. for now, though, i'm not as comfortable with either the Bash shell or *nix-like paths, as w/ CMD.

And so far it's okay. I installed the packages under Bash with MSYS2 'pacman' ... then CMake under CMD *did find* three of them (or so).


I just tried cmake in Bash. Same thing. So I added this to my .bashrc

export PATH="$PATH:/c/msys32/mingw32/include:/c/msys32/mingw32/lib"

And it found Boost but cr*pped on SDL2. Looking in FindSDL2.cmake shows this:

find_path(SDL2_INCLUDE_DIR SDL.h $ENV{PROGRAMFILES}/SDL2/include DOC "The directory where SDL.h resides")
find_library(SDL2_LIBRARY NAMES SDL2 PATHS $ENV{PROGRAMFILES}/SDL2/lib DOC "The SDL2 library")

You might want to look into the stock (CMake v3.3.2) FindZLIB.cmake, since that script finds zlib under both CMD and Bash -- zlib is in my C:\msys32\mingw32\include & \lib, like the others. At a glance it seems to be finding the path to zlib in the Registry.

uh, it's not in my registry. Further inspection shows that the stock FindZLIB module is finding zlib at

C:/msys32/usr/lib/libz.dll.a

that is, it's not finding the 'zlib-devel' package (headers + libraries) in \mingw32 but the (much simpler) 'zlib' package in my so-called user folder. However, the stock FindBoost script probly finds the correct paths (after I export the system PATH in Bash), but whoever wrote that was doing some pretty heavy-duty scripting ...


if you really want raw data,
http://pastebin.com/dgXRqmdz

**Comment by kevL** [comment]
Ps.

MinGW is putting includes in
C:\MinGW\include (eg. zlib.h, iconv.h, \lzma\version.h, libxml2\libxml\xpath.h)

and libs in
C:\MinGW\lib (eg. libvorbis.a, libvorbis.dll.a, libz.a, libz.dll.a)


while MinGW-w64 lets the MSYS2 pacman app use the directories noted earlier.


(ofc there are many other lib & bin & include dirs scattered throughout both installations, but those are the ones I notice relevant to xoreos' externals)

**Pull request merged**
