### PR TITLE
Refactor CharacterGenerationInfo in KotOR games

### PR DESCRIPTION
**Pull request by seedhartha**
This PR extracts creature and model creation from the CharacterGenerationInfo class, which removes a circular dependency on the Creature class and, IMO, better represents the class intent.

### CODE REVIEW

**Comment by DrMcCoy** [comment]
Hmm, but the classes in KotOR and KotOR2 are different. So now you have KotOR-only stuff in KotORBase

**Comment by seedhartha** [comment]
True. Character and CharacterGenerationInfo classes should be subclassed in KotOR as well.

**Comment by seedhartha** [comment]
I have extracted KotOR-specific code for creatures, chargeninfo and saved games from the base engine. As for the issues you were having, they seem to have existed for some time before the base engine PR. It can wait for a separate PR, I think.

**Comment by DrMcCoy** [comment]
(Another one, when selecting a character class (a female soldier, I think it was): https://gist.github.com/DrMcCoy/78899f951dd27dd768d87fb7b7e7daf9 )

**Comment by DrMcCoy** [comment]
Ah, nope, that one now always happens with this PR applied. When clicking on "OK" in the portrait selection.

**Comment by seedhartha** [comment]
Fixed.

**Comment by seedhartha** [comment]
I also fixed the sanitizer errors you mentioned. Not sure about the segfault though.

**Comment by DrMcCoy** [comment]
The Sanitizers now complain within the pathfinding code, when Trask wants to move to the PC: https://gist.github.com/DrMcCoy/84a443f4c85c728fde56f694843c4aa0

**Comment by seedhartha** [comment]
I guess it has to do with the commits Supermanu pushed recently.

**Comment by DrMcCoy** [comment]
Ah, yes, you're right. master - Supermanu's changes + this PR works.

**Comment by DrMcCoy** [comment]
Okay, merged as 1b04f4792...15f47ff05, thanks! :)

I'll open an issue for the new pathfinding thing.

**Pull request closed without merging**
