### PR TITLE
BUILD: Add arm64 build and exclude osx from it

### PR DESCRIPTION
**Pull request by Nostritius**
After i realized, that travis now offers the possibility to build for arm, i added some extensions to the travis file to build all linux targets for arm64.

### CODE REVIEW

**Comment by DrMcCoy** [comment]
Oh, nice. But you also need to make sure Coverity Scan doesn't trigger for arm builds. I.e. you need to add that to the `coverity_scan_run_condition`.

**Comment by Nostritius** [comment]
I've added now a condition to the coverity scan to only compile with x86_64 architecture

**Comment by DrMcCoy** [comment]
Merged, thanks! :)

**Comment by DrMcCoy** [comment]
Oh, btw, can you do that for xoreos-tools and phaethon as well, please?

**Comment by Nostritius** [comment]
Of course, i will do so

**Pull request merged**
