### PR TITLE
KOTOR: NPC equipment, in-game menus, cursor mechanics, lightsabers, fixes

### PR DESCRIPTION
**Pull request by seedhartha**
This PR:
- Implements loading and changing of NPC equipment.
- Implements changing the party leader from in-game menus.
- Implements weapon wield animation for two swords and two pistols.
- Implements cursor mechanics from the original games.
- Fixes frame time miscalculations when closing in-game menus (teleporting characters).
- Fixes loading equipped body models for PC.
- Fixes loading and displaying of lightsaber models. Also, windows on the Endar Spire.

### CODE REVIEW

**Comment by DrMcCoy** [comment]
Neat, thanks! :)

I'll look at it more closely in the evening.

**Comment by DrMcCoy** [comment]
Seems like you introduced a memory oops during the saber loading: https://gist.github.com/DrMcCoy/3a9b8ba70655add34bff181c8c6613fe

**Comment by seedhartha** [comment]
Yeah, my bad :) Fixed the overflow error.

**Comment by DrMcCoy** [comment]
Merged as ccd06116a...12bbc2c06, thanks! :)

**Pull request closed without merging**
