### PR TITLE
KOTOR: Add barebone resolution submenu to graphics menu

### PR DESCRIPTION
**Pull request by Nostritius**
This PR implements the barebone resolution menu for the kotor options menu

### CODE REVIEW

**Comment by DrMcCoy** [comment]
...Why does the border around the "Advanced Options" button vanish when I click on Cancel in the resolution menu? O_o

**Comment by DrMcCoy** [comment]
Apart from this oddity (which is probably not the fault of this PR as such), this looks good to me. Merged as 55ecfd009cf2c18c4c4929158daa325a67d16fae, thanks! :)

**Comment by Nostritius** [comment]
Could you file a bug for this? So I won't forget to look after this.

**Comment by DrMcCoy** [comment]
Right, good idea. #231 it is, now.

**Pull request closed without merging**
